/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4ek7yevYSmZU9MaEHzjjyJ
// Component: OPun2yHK_93c

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NewsletterComponent from "../../NewsletterComponent"; // plasmic-import: FL9UE5cenYH-/component

import { useScreenVariants as useScreenVariantsqAyk5ZgNfB } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: q_ayk5ZGNfB_/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4ek7yevYSmZU9MaEHzjjyJ/projectcss
import sty from "./PlasmicSectionMeetTheTeam.module.css"; // plasmic-import: OPun2yHK_93c/css

createPlasmicElementProxy;

export type PlasmicSectionMeetTheTeam__VariantMembers = {};
export type PlasmicSectionMeetTheTeam__VariantsArgs = {};
type VariantPropType = keyof PlasmicSectionMeetTheTeam__VariantsArgs;
export const PlasmicSectionMeetTheTeam__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSectionMeetTheTeam__ArgsType = {};
type ArgPropType = keyof PlasmicSectionMeetTheTeam__ArgsType;
export const PlasmicSectionMeetTheTeam__ArgProps = new Array<ArgPropType>();

export type PlasmicSectionMeetTheTeam__OverridesType = {
  root?: Flex__<"div">;
  section?: Flex__<"section">;
  freeBox?: Flex__<"div">;
  h2?: Flex__<"h2">;
  img?: Flex__<typeof PlasmicImg__>;
  text?: Flex__<"div">;
  newsletterComponent?: Flex__<typeof NewsletterComponent>;
};

export interface DefaultSectionMeetTheTeamProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSectionMeetTheTeam__RenderFunc(props: {
  variants: PlasmicSectionMeetTheTeam__VariantsArgs;
  args: PlasmicSectionMeetTheTeam__ArgsType;
  overrides: PlasmicSectionMeetTheTeam__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqAyk5ZgNfB()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <section
        data-plasmic-name={"section"}
        data-plasmic-override={overrides.section}
        className={classNames(projectcss.all, sty.section)}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          <h2
            data-plasmic-name={"h2"}
            data-plasmic-override={overrides.h2}
            className={classNames(
              projectcss.all,
              projectcss.h2,
              projectcss.__wab_text,
              sty.h2
            )}
          >
            {hasVariant(globalVariants, "screen", "mobileOnly")
              ? "Meet the Team"
              : "Meet our Instructors & Staff"}
          </h2>
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"800px"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/halcyon_website/images/image13.png",
              fullWidth: 4096,
              fullHeight: 2732,
              aspectRatio: undefined
            }}
          />

          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            {"Individual Teacher Bios Coming Soon"}
          </div>
        </Stack__>
        <NewsletterComponent
          data-plasmic-name={"newsletterComponent"}
          data-plasmic-override={overrides.newsletterComponent}
          className={classNames("__wab_instance", sty.newsletterComponent)}
        />
      </section>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "section",
    "freeBox",
    "h2",
    "img",
    "text",
    "newsletterComponent"
  ],
  section: ["section", "freeBox", "h2", "img", "text", "newsletterComponent"],
  freeBox: ["freeBox", "h2", "img", "text"],
  h2: ["h2"],
  img: ["img"],
  text: ["text"],
  newsletterComponent: ["newsletterComponent"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  section: "section";
  freeBox: "div";
  h2: "h2";
  img: typeof PlasmicImg__;
  text: "div";
  newsletterComponent: typeof NewsletterComponent;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSectionMeetTheTeam__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSectionMeetTheTeam__VariantsArgs;
    args?: PlasmicSectionMeetTheTeam__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSectionMeetTheTeam__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSectionMeetTheTeam__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSectionMeetTheTeam__ArgProps,
          internalVariantPropNames: PlasmicSectionMeetTheTeam__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSectionMeetTheTeam__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSectionMeetTheTeam";
  } else {
    func.displayName = `PlasmicSectionMeetTheTeam.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionMeetTheTeam = Object.assign(
  // Top-level PlasmicSectionMeetTheTeam renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    freeBox: makeNodeComponent("freeBox"),
    h2: makeNodeComponent("h2"),
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),
    newsletterComponent: makeNodeComponent("newsletterComponent"),

    // Metadata about props expected for PlasmicSectionMeetTheTeam
    internalVariantProps: PlasmicSectionMeetTheTeam__VariantProps,
    internalArgProps: PlasmicSectionMeetTheTeam__ArgProps
  }
);

export default PlasmicSectionMeetTheTeam;
/* prettier-ignore-end */
