/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4ek7yevYSmZU9MaEHzjjyJ
// Component: DGQUyhUXa44C

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { AntdInputNumber } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4ek7yevYSmZU9MaEHzjjyJ/projectcss
import sty from "./PlasmicPrivatesForm2.module.css"; // plasmic-import: DGQUyhUXa44C/css

createPlasmicElementProxy;

export type PlasmicPrivatesForm2__VariantMembers = {};
export type PlasmicPrivatesForm2__VariantsArgs = {};
type VariantPropType = keyof PlasmicPrivatesForm2__VariantsArgs;
export const PlasmicPrivatesForm2__VariantProps = new Array<VariantPropType>();

export type PlasmicPrivatesForm2__ArgsType = {};
type ArgPropType = keyof PlasmicPrivatesForm2__ArgsType;
export const PlasmicPrivatesForm2__ArgProps = new Array<ArgPropType>();

export type PlasmicPrivatesForm2__OverridesType = {
  root?: Flex__<"div">;
  privatesForm2?: Flex__<typeof FormWrapper>;
  firstName?: Flex__<typeof FormItemWrapper>;
  firstNameText?: Flex__<"div">;
  firstNameInput?: Flex__<typeof AntdInput>;
  lastName?: Flex__<typeof FormItemWrapper>;
  lastNameText?: Flex__<"div">;
  lastNameInput?: Flex__<typeof AntdInput>;
  phone?: Flex__<typeof FormItemWrapper>;
  phoneText?: Flex__<"div">;
  phoneInput?: Flex__<typeof AntdInput>;
  email?: Flex__<typeof FormItemWrapper>;
  emailText?: Flex__<"div">;
  emailInput?: Flex__<typeof AntdInput>;
  freeBox?: Flex__<"div">;
  interestedIn?: Flex__<typeof FormItemWrapper>;
  interestedInText?: Flex__<"div">;
  interestedInSelect?: Flex__<typeof AntdSelect>;
  numberGuests?: Flex__<typeof FormItemWrapper>;
  numberGuestsText?: Flex__<"div">;
  guestsNumberInput?: Flex__<typeof AntdInputNumber>;
  comments?: Flex__<typeof FormItemWrapper>;
  commentsText?: Flex__<"div">;
  commentsInput?: Flex__<typeof AntdInput>;
  input6?: Flex__<typeof AntdInput>;
  numberInput2?: Flex__<typeof AntdInputNumber>;
  submitButton?: Flex__<typeof AntdButton>;
};

export interface DefaultPrivatesForm2Props {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPrivatesForm2__RenderFunc(props: {
  variants: PlasmicPrivatesForm2__VariantsArgs;
  args: PlasmicPrivatesForm2__ArgsType;
  overrides: PlasmicPrivatesForm2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "privatesForm2.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "privatesForm2",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "privatesForm2.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "privatesForm2",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "firstNameInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "lastNameInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "phoneInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "emailInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "interestedInSelect.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "guestsNumberInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "commentsInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input6.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "numberInput2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__yZ4Dx
        )}
      >
        {"Privates Inquiry Form"}
      </div>
      {(() => {
        const child$Props = {
          className: classNames("__wab_instance", sty.privatesForm2),
          extendedOnValuesChange: async (...eventArgs: any) => {
            generateStateOnChangePropForCodeComponents(
              $state,
              "value",
              ["privatesForm2", "value"],
              FormWrapper_Helpers
            ).apply(null, eventArgs);
          },
          formItems: [
            { label: "Name", name: "name", inputType: "Text" },
            { label: "Message", name: "message", inputType: "Text Area" }
          ],
          labelCol: { span: 8, horizontalOnly: true },
          layout: "vertical",
          mode: "advanced",
          onFinish: async values => {
            const $steps = {};

            $steps["defaultSubmit"] = true
              ? (() => {
                  const actionArgs = {
                    dataOp: {
                      sourceId: "wp17K6dTyNJfMVu3RB7ygH",
                      opId: "5c1fbbd2-cada-4407-817b-171d8f26bb58",
                      userArgs: {
                        variables: [$state.privatesForm2.value]
                      },
                      cacheKey: null,
                      invalidatedKeys: ["plasmic_refresh_all"],
                      roleId: null
                    }
                  };
                  return (async ({ dataOp, continueOnError }) => {
                    try {
                      const response = await executePlasmicDataOp(dataOp, {
                        userAuthToken: dataSourcesCtx?.userAuthToken,
                        user: dataSourcesCtx?.user
                      });
                      await plasmicInvalidate(dataOp.invalidatedKeys);
                      return response;
                    } catch (e) {
                      if (!continueOnError) {
                        throw e;
                      }
                      return e;
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["defaultSubmit"] != null &&
              typeof $steps["defaultSubmit"] === "object" &&
              typeof $steps["defaultSubmit"].then === "function"
            ) {
              $steps["defaultSubmit"] = await $steps["defaultSubmit"];
            }
          },
          onIsSubmittingChange: async (...eventArgs: any) => {
            generateStateOnChangePropForCodeComponents(
              $state,
              "isSubmitting",
              ["privatesForm2", "isSubmitting"],
              FormWrapper_Helpers
            ).apply(null, eventArgs);
          },
          ref: ref => {
            $refs["privatesForm2"] = ref;
          },
          submitSlot: null,
          wrapperCol: { span: 16, horizontalOnly: true }
        };
        initializeCodeComponentStates(
          $state,
          [
            {
              name: "value",
              plasmicStateName: "privatesForm2.value"
            },
            {
              name: "isSubmitting",
              plasmicStateName: "privatesForm2.isSubmitting"
            }
          ],
          [],
          FormWrapper_Helpers ?? {},
          child$Props
        );

        return (
          <FormWrapper
            data-plasmic-name={"privatesForm2"}
            data-plasmic-override={overrides.privatesForm2}
            {...child$Props}
          >
            <FormItemWrapper
              data-plasmic-name={"firstName"}
              data-plasmic-override={overrides.firstName}
              className={classNames("__wab_instance", sty.firstName)}
              initialValue={undefined}
              label={
                <div
                  data-plasmic-name={"firstNameText"}
                  data-plasmic-override={overrides.firstNameText}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.firstNameText
                  )}
                >
                  {"First Name"}
                </div>
              }
              name={"first_name"}
            >
              {(() => {
                const child$Props = {
                  bordered: true,
                  className: classNames("__wab_instance", sty.firstNameInput),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["firstNameInput", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, [
                    "firstNameInput",
                    "value"
                  ])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "firstNameInput.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"firstNameInput"}
                    data-plasmic-override={overrides.firstNameInput}
                    {...child$Props}
                  />
                );
              })()}
            </FormItemWrapper>
            <FormItemWrapper
              data-plasmic-name={"lastName"}
              data-plasmic-override={overrides.lastName}
              className={classNames("__wab_instance", sty.lastName)}
              initialValue={undefined}
              label={
                <div
                  data-plasmic-name={"lastNameText"}
                  data-plasmic-override={overrides.lastNameText}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.lastNameText
                  )}
                >
                  {"Last Name"}
                </div>
              }
              name={"last_name"}
            >
              {(() => {
                const child$Props = {
                  className: classNames("__wab_instance", sty.lastNameInput),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["lastNameInput", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, [
                    "lastNameInput",
                    "value"
                  ])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "lastNameInput.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"lastNameInput"}
                    data-plasmic-override={overrides.lastNameInput}
                    {...child$Props}
                  />
                );
              })()}
            </FormItemWrapper>
            <FormItemWrapper
              data-plasmic-name={"phone"}
              data-plasmic-override={overrides.phone}
              className={classNames("__wab_instance", sty.phone)}
              initialValue={undefined}
              label={
                <div
                  data-plasmic-name={"phoneText"}
                  data-plasmic-override={overrides.phoneText}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.phoneText
                  )}
                >
                  {"Phone"}
                </div>
              }
              name={"phone"}
              rules={[
                {
                  ruleType: "advanced",
                  custom: (rule, value) => {
                    return (() => {
                      function formatPhoneNumber(value) {
                        let cleaned = value.replace(/\D/g, "");
                        if (cleaned.length > 10) {
                          cleaned = cleaned.substring(0, 10);
                        }
                        let formatted = cleaned;
                        if (cleaned.length > 6) {
                          formatted = `(${cleaned.substring(
                            0,
                            3
                          )}) ${cleaned.substring(3, 6)}-${cleaned.substring(
                            6
                          )}`;
                        } else if (cleaned.length > 3) {
                          formatted = `(${cleaned.substring(
                            0,
                            3
                          )}) ${cleaned.substring(3)}`;
                        }
                        return formatted;
                      }
                      return ($state.privatesForm2.value.phone =
                        formatPhoneNumber($state.privatesForm2.value.phone));
                    })();
                  }
                }
              ]}
              validateTrigger={["onChange"]}
            >
              {(() => {
                const child$Props = {
                  className: classNames("__wab_instance", sty.phoneInput),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["phoneInput", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, ["phoneInput", "value"])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "phoneInput.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"phoneInput"}
                    data-plasmic-override={overrides.phoneInput}
                    {...child$Props}
                  />
                );
              })()}
            </FormItemWrapper>
            <FormItemWrapper
              data-plasmic-name={"email"}
              data-plasmic-override={overrides.email}
              className={classNames("__wab_instance", sty.email)}
              initialValue={undefined}
              label={
                <div
                  data-plasmic-name={"emailText"}
                  data-plasmic-override={overrides.emailText}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.emailText
                  )}
                >
                  {"Email"}
                </div>
              }
              name={"email"}
              rules={[
                {
                  ruleType: "advanced",
                  custom: (rule, value) => {
                    return (() => {
                      function isValidEmail(value) {
                        return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
                      }
                      return isValidEmail($state.privatesForm2.value.email);
                    })();
                  }
                }
              ]}
            >
              {(() => {
                const child$Props = {
                  className: classNames("__wab_instance", sty.emailInput),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["emailInput", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, ["emailInput", "value"])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "emailInput.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"emailInput"}
                    data-plasmic-override={overrides.emailInput}
                    {...child$Props}
                  />
                );
              })()}
            </FormItemWrapper>
            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <FormItemWrapper
                data-plasmic-name={"interestedIn"}
                data-plasmic-override={overrides.interestedIn}
                className={classNames("__wab_instance", sty.interestedIn)}
                initialValue={undefined}
                label={
                  <div
                    data-plasmic-name={"interestedInText"}
                    data-plasmic-override={overrides.interestedInText}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.interestedInText
                    )}
                  >
                    {"Interested In"}
                  </div>
                }
                name={"privates_type"}
              >
                <AntdSelect
                  data-plasmic-name={"interestedInSelect"}
                  data-plasmic-override={overrides.interestedInSelect}
                  className={classNames(
                    "__wab_instance",
                    sty.interestedInSelect
                  )}
                  defaultStylesClassName={classNames(
                    projectcss.root_reset,
                    projectcss.plasmic_default_styles,
                    projectcss.plasmic_mixins,
                    projectcss.plasmic_tokens,
                    plasmic_antd_5_hostless_css.plasmic_tokens
                  )}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "interestedInSelect",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  options={(() => {
                    const __composite = [
                      { type: "option", label: null, value: null },
                      { type: "option", label: null, value: null },
                      { type: "option", label: null, value: null },
                      { type: "option", label: null, value: null },
                      { type: null, label: null, value: null }
                    ];
                    __composite["0"]["label"] = "Private Pilates";
                    __composite["0"]["value"] = "Private Pilates";
                    __composite["1"]["label"] = "Private Yoga";
                    __composite["1"]["value"] = "Private Yoga";
                    __composite["2"]["label"] = "Studio Rental";
                    __composite["2"]["value"] = "Studio Rental";
                    __composite["3"]["label"] = "Photo Shoot";
                    __composite["3"]["value"] = "Photo Shoot";
                    __composite["4"]["type"] = "option";
                    __composite["4"]["label"] = "Other";
                    __composite["4"]["value"] = "Other";
                    return __composite;
                  })()}
                  placeholder={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kJqN1
                      )}
                    >
                      {"Select..."}
                    </div>
                  }
                  popupScopeClassName={sty["interestedInSelect__popup"]}
                  triggerClassName={classNames({
                    [sty["pcls_RyN-1n2DTmJ8"]]: true
                  })}
                  value={generateStateValueProp($state, [
                    "interestedInSelect",
                    "value"
                  ])}
                />
              </FormItemWrapper>
              <FormItemWrapper
                data-plasmic-name={"numberGuests"}
                data-plasmic-override={overrides.numberGuests}
                className={classNames("__wab_instance", sty.numberGuests)}
                initialValue={undefined}
                label={
                  <div
                    data-plasmic-name={"numberGuestsText"}
                    data-plasmic-override={overrides.numberGuestsText}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.numberGuestsText
                    )}
                  >
                    {"Number of Guests"}
                  </div>
                }
                name={"number_guests"}
              >
                <AntdInputNumber
                  data-plasmic-name={"guestsNumberInput"}
                  data-plasmic-override={overrides.guestsNumberInput}
                  className={classNames(
                    "__wab_instance",
                    sty.guestsNumberInput
                  )}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "guestsNumberInput",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  type={"number"}
                  value={generateStateValueProp($state, [
                    "guestsNumberInput",
                    "value"
                  ])}
                />
              </FormItemWrapper>
            </div>
            <FormItemWrapper
              data-plasmic-name={"comments"}
              data-plasmic-override={overrides.comments}
              className={classNames("__wab_instance", sty.comments)}
              initialValue={undefined}
              label={
                <div
                  data-plasmic-name={"commentsText"}
                  data-plasmic-override={overrides.commentsText}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.commentsText
                  )}
                >
                  {"Comments"}
                </div>
              }
              name={"comments"}
            >
              {(() => {
                const child$Props = {
                  className: classNames("__wab_instance", sty.commentsInput),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["commentsInput", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  size: "large",
                  value: generateStateValueProp($state, [
                    "commentsInput",
                    "value"
                  ])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "commentsInput.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"commentsInput"}
                    data-plasmic-override={overrides.commentsInput}
                    {...child$Props}
                  />
                );
              })()}
            </FormItemWrapper>
            <FormItemWrapper
              className={classNames("__wab_instance", sty.formField___5Zm52)}
              hidden={true}
              initialValue={undefined}
              label={"created_at"}
              name={"created_at"}
            >
              {(() => {
                const child$Props = {
                  className: classNames("__wab_instance", sty.input6),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["input6", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, ["input6", "value"])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "input6.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"input6"}
                    data-plasmic-override={overrides.input6}
                    {...child$Props}
                  />
                );
              })()}
            </FormItemWrapper>
            <FormItemWrapper
              className={classNames("__wab_instance", sty.formField___9Ekd2)}
              hidden={true}
              initialValue={undefined}
              label={"privates_id"}
              name={"privates_id"}
            >
              <AntdInputNumber
                data-plasmic-name={"numberInput2"}
                data-plasmic-override={overrides.numberInput2}
                className={classNames("__wab_instance", sty.numberInput2)}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "numberInput2",
                    "value"
                  ]).apply(null, eventArgs);
                }}
                type={"number"}
                value={generateStateValueProp($state, [
                  "numberInput2",
                  "value"
                ])}
              />
            </FormItemWrapper>
            <AntdButton
              data-plasmic-name={"submitButton"}
              data-plasmic-override={overrides.submitButton}
              className={classNames("__wab_instance", sty.submitButton)}
              size={"large"}
              submitsForm={true}
              type={"primary"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4ZLbw
                )}
              >
                {"Submit"}
              </div>
            </AntdButton>
          </FormWrapper>
        );
      })()}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "privatesForm2",
    "firstName",
    "firstNameText",
    "firstNameInput",
    "lastName",
    "lastNameText",
    "lastNameInput",
    "phone",
    "phoneText",
    "phoneInput",
    "email",
    "emailText",
    "emailInput",
    "freeBox",
    "interestedIn",
    "interestedInText",
    "interestedInSelect",
    "numberGuests",
    "numberGuestsText",
    "guestsNumberInput",
    "comments",
    "commentsText",
    "commentsInput",
    "input6",
    "numberInput2",
    "submitButton"
  ],
  privatesForm2: [
    "privatesForm2",
    "firstName",
    "firstNameText",
    "firstNameInput",
    "lastName",
    "lastNameText",
    "lastNameInput",
    "phone",
    "phoneText",
    "phoneInput",
    "email",
    "emailText",
    "emailInput",
    "freeBox",
    "interestedIn",
    "interestedInText",
    "interestedInSelect",
    "numberGuests",
    "numberGuestsText",
    "guestsNumberInput",
    "comments",
    "commentsText",
    "commentsInput",
    "input6",
    "numberInput2",
    "submitButton"
  ],
  firstName: ["firstName", "firstNameText", "firstNameInput"],
  firstNameText: ["firstNameText"],
  firstNameInput: ["firstNameInput"],
  lastName: ["lastName", "lastNameText", "lastNameInput"],
  lastNameText: ["lastNameText"],
  lastNameInput: ["lastNameInput"],
  phone: ["phone", "phoneText", "phoneInput"],
  phoneText: ["phoneText"],
  phoneInput: ["phoneInput"],
  email: ["email", "emailText", "emailInput"],
  emailText: ["emailText"],
  emailInput: ["emailInput"],
  freeBox: [
    "freeBox",
    "interestedIn",
    "interestedInText",
    "interestedInSelect",
    "numberGuests",
    "numberGuestsText",
    "guestsNumberInput"
  ],
  interestedIn: ["interestedIn", "interestedInText", "interestedInSelect"],
  interestedInText: ["interestedInText"],
  interestedInSelect: ["interestedInSelect"],
  numberGuests: ["numberGuests", "numberGuestsText", "guestsNumberInput"],
  numberGuestsText: ["numberGuestsText"],
  guestsNumberInput: ["guestsNumberInput"],
  comments: ["comments", "commentsText", "commentsInput"],
  commentsText: ["commentsText"],
  commentsInput: ["commentsInput"],
  input6: ["input6"],
  numberInput2: ["numberInput2"],
  submitButton: ["submitButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  privatesForm2: typeof FormWrapper;
  firstName: typeof FormItemWrapper;
  firstNameText: "div";
  firstNameInput: typeof AntdInput;
  lastName: typeof FormItemWrapper;
  lastNameText: "div";
  lastNameInput: typeof AntdInput;
  phone: typeof FormItemWrapper;
  phoneText: "div";
  phoneInput: typeof AntdInput;
  email: typeof FormItemWrapper;
  emailText: "div";
  emailInput: typeof AntdInput;
  freeBox: "div";
  interestedIn: typeof FormItemWrapper;
  interestedInText: "div";
  interestedInSelect: typeof AntdSelect;
  numberGuests: typeof FormItemWrapper;
  numberGuestsText: "div";
  guestsNumberInput: typeof AntdInputNumber;
  comments: typeof FormItemWrapper;
  commentsText: "div";
  commentsInput: typeof AntdInput;
  input6: typeof AntdInput;
  numberInput2: typeof AntdInputNumber;
  submitButton: typeof AntdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPrivatesForm2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPrivatesForm2__VariantsArgs;
    args?: PlasmicPrivatesForm2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPrivatesForm2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPrivatesForm2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPrivatesForm2__ArgProps,
          internalVariantPropNames: PlasmicPrivatesForm2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPrivatesForm2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPrivatesForm2";
  } else {
    func.displayName = `PlasmicPrivatesForm2.${nodeName}`;
  }
  return func;
}

export const PlasmicPrivatesForm2 = Object.assign(
  // Top-level PlasmicPrivatesForm2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    privatesForm2: makeNodeComponent("privatesForm2"),
    firstName: makeNodeComponent("firstName"),
    firstNameText: makeNodeComponent("firstNameText"),
    firstNameInput: makeNodeComponent("firstNameInput"),
    lastName: makeNodeComponent("lastName"),
    lastNameText: makeNodeComponent("lastNameText"),
    lastNameInput: makeNodeComponent("lastNameInput"),
    phone: makeNodeComponent("phone"),
    phoneText: makeNodeComponent("phoneText"),
    phoneInput: makeNodeComponent("phoneInput"),
    email: makeNodeComponent("email"),
    emailText: makeNodeComponent("emailText"),
    emailInput: makeNodeComponent("emailInput"),
    freeBox: makeNodeComponent("freeBox"),
    interestedIn: makeNodeComponent("interestedIn"),
    interestedInText: makeNodeComponent("interestedInText"),
    interestedInSelect: makeNodeComponent("interestedInSelect"),
    numberGuests: makeNodeComponent("numberGuests"),
    numberGuestsText: makeNodeComponent("numberGuestsText"),
    guestsNumberInput: makeNodeComponent("guestsNumberInput"),
    comments: makeNodeComponent("comments"),
    commentsText: makeNodeComponent("commentsText"),
    commentsInput: makeNodeComponent("commentsInput"),
    input6: makeNodeComponent("input6"),
    numberInput2: makeNodeComponent("numberInput2"),
    submitButton: makeNodeComponent("submitButton"),

    // Metadata about props expected for PlasmicPrivatesForm2
    internalVariantProps: PlasmicPrivatesForm2__VariantProps,
    internalArgProps: PlasmicPrivatesForm2__ArgProps
  }
);

export default PlasmicPrivatesForm2;
/* prettier-ignore-end */
