// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHomeSection,
  DefaultHomeSectionProps
} from "./plasmic/halcyon_website/PlasmicHomeSection";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { useRouter } from "next/router";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface HomeSectionProps extends Omit<DefaultHomeSectionProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultHomeSectionProps altogether and have
// total control over the props for your component.
export interface HomeSectionProps extends DefaultHomeSectionProps {}

function HomeSection_(
  props: HomeSectionProps,
  ref: HTMLElementRefOf<"section">
) {
  const router = useRouter();

  return (
    <PlasmicHomeSection
      root={{ ref }}
      {...props}
      membershipsButton={{
        props: {
          onClick: () => {
            router.push("/memberships");
          },
        },
      }}
    />
  );
}

const HomeSection = React.forwardRef(HomeSection_);
export default HomeSection;
